# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  collation: utf8_unicode_ci

development:
  <<: *default
  database: aidar
  username: root
  password: gkbcrby83

test:
  <<: *default
  database: aidar_test
  username: root
  password: gkbcrby83

